import Link from "next/link";
import Header from "@/components/Header";
import OrvenLogo from "@/components/OrvenLogo";
import { createClient } from "@/lib/supabase/server";
import DashboardAccountMenu from "@/components/DashboardAccountMenu";
import HomeSocialFeed from "@/components/HomeSocialFeed";
import HomeProfileStats from "@/components/HomeProfileStats";
import LiveSearch from "@/components/LiveSearch";
import SocialPostCard from "@/components/SocialPostCard";
import PresenceHeartbeat from "@/components/PresenceHeartbeat";

const selectPosts="id,content,created_at,updated_at,image_url,author_id,profiles:profiles!posts_author_id_fkey_profiles(username,display_name,avatar_url),post_likes(user_id),post_comments(id),post_images(id,image_url,position)";
export default async function Home(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();
 if(!user){const {data:recent}=await supabase.from("posts").select(selectPosts).order("created_at",{ascending:false}).limit(40);return <><Header user={null}/><main className="publicCommunityHome"><section className="publicFeedHeading"><div><span className="goldEyebrow">ORVENSMP COMMUNITY</span><h1>Latest from the community</h1><p>Discover what Minecraft creators, server owners and players are sharing right now.</p></div></section><section className="publicPostFeed">{(recent||[]).length?(recent||[]).map((p:any)=><SocialPostCard key={p.id} post={p} currentUserId={null}/>):<div className="emptyFeed"><span>⬡</span><h2>No posts yet</h2><p>The first community posts will appear here.</p></div>}</section></main></>}
 const {data:profile}=await supabase.from("profiles").select("*").eq("id",user.id).maybeSingle();const username=profile?.username||user.email?.split("@")[0]||"player",name=profile?.display_name||username,avatar=profile?.avatar_url;
 const [{data:allPosts},{data:myFollowing},{data:myFollowers},{count:postCount},{count:followerCount},{count:followingCount}]=await Promise.all([supabase.from("posts").select(selectPosts).order("created_at",{ascending:false}).limit(80),supabase.from("follows").select("following_id").eq("follower_id",user.id),supabase.from("follows").select("follower_id").eq("following_id",user.id),supabase.from("posts").select("*",{count:"exact",head:true}).eq("author_id",user.id),supabase.from("follows").select("*",{count:"exact",head:true}).eq("following_id",user.id),supabase.from("follows").select("*",{count:"exact",head:true}).eq("follower_id",user.id)]);
 const following=new Set((myFollowing||[]).map(x=>x.following_id)),followers=new Set((myFollowers||[]).map(x=>x.follower_id));const priority=(id:string)=>following.has(id)&&followers.has(id)?0:following.has(id)?1:2;const posts=[...(allPosts||[])].sort((a,b)=>priority(a.author_id)-priority(b.author_id)||new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).slice(0,50);
 return <div className="appShell"><PresenceHeartbeat userId={user.id}/><aside className="sideNav"><OrvenLogo/><nav><Link className="active" href="/">⌂ <span>Home</span></Link><Link href="/profile/me">♙ <span>Profile</span></Link><a href="#explore">◇ <span>Explore</span></a><Link href="/notifications">♧ <span>Notifications</span></Link><Link href="/messages">✉ <span>Messages</span></Link><Link href="/settings">⚙ <span>Settings</span></Link></nav></aside><div className="appMain"><header className="dashboardTop"><LiveSearch variant="dashboard"/><div className="topActions"><button className="iconButton">♢</button><DashboardAccountMenu name={name} username={username} avatar={avatar} role={profile?.role||"member"}/></div></header><div className="dashboardGrid"><main className="feedColumn"><HomeSocialFeed userId={user.id} name={name} username={username} avatar={avatar} initialPosts={posts as any}/></main><aside className="rightRail"><section className="railCard profileCard"><div className="railTitle"><b>♛ Your Profile</b><Link href="/profile/me">View Profile →</Link></div><div className="profileIdentity">{avatar?<img src={avatar} alt=""/>:<div className="bigAvatar">{name.slice(0,1).toUpperCase()}</div>}<div><strong>{name}</strong><span>@{username}</span></div></div><HomeProfileStats posts={postCount||0} followers={followerCount||0} following={followingCount||0}/><Link className="editProfileButton" href="/settings">✎ Edit Profile</Link></section></aside></div></div></div>}
