"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Person={id:string;username:string;display_name:string|null;avatar_url:string|null;last_seen_at:string|null};
type Msg={id:string;sender_id:string;recipient_id:string;content:string;created_at:string;read_at:string|null};
const online=(x:string|null)=>!!x&&Date.now()-new Date(x).getTime()<150000;
export default function MessagesClient({me,people,initialWith}:{me:Person;people:Person[];initialWith?:string|null}){
 const supabase=useMemo(()=>createClient(),[]), [selected,setSelected]=useState(initialWith||people[0]?.id||null),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(""),[busy,setBusy]=useState(false);const end=useRef<HTMLDivElement>(null);
 const person=people.find(p=>p.id===selected)||null;
 async function load(){if(!selected)return;const {data}=await supabase.from("direct_messages").select("id,sender_id,recipient_id,content,created_at,read_at").or(`and(sender_id.eq.${me.id},recipient_id.eq.${selected}),and(sender_id.eq.${selected},recipient_id.eq.${me.id})`).order("created_at",{ascending:true}).limit(250);setMessages((data||[]) as Msg[]);await supabase.from("direct_messages").update({read_at:new Date().toISOString()}).eq("sender_id",selected).eq("recipient_id",me.id).is("read_at",null)}
 useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[selected]);useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[messages]);
 async function send(e:FormEvent){e.preventDefault();const content=text.trim();if(!content||!selected)return;setBusy(true);const {data,error}=await supabase.from("direct_messages").insert({sender_id:me.id,recipient_id:selected,content}).select("id,sender_id,recipient_id,content,created_at,read_at").single();setBusy(false);if(!error&&data){setMessages(x=>[...x,data as Msg]);setText("")}}
 return <div className="messagesShell"><aside className="conversationList"><div className="messageSideTitle"><h2>Messages</h2><span>{people.length} people</span></div>{people.length?people.map(p=><button className={selected===p.id?"active":""} onClick={()=>setSelected(p.id)} key={p.id}><span className="dmAvatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:(p.display_name||p.username).slice(0,1).toUpperCase()}<i className={online(p.last_seen_at)?"online":"offline"}/></span><span><b>{p.display_name||p.username}</b><small>@{p.username} · {online(p.last_seen_at)?"Online":"Offline"}</small></span></button>):<p className="noConversations">Search for a member and open their profile to start a message.</p>}</aside><section className="messageThread">{person?<><header><div className="dmAvatar">{person.avatar_url?<img src={person.avatar_url} alt=""/>:(person.display_name||person.username).slice(0,1).toUpperCase()}<i className={online(person.last_seen_at)?"online":"offline"}/></div><div><Link href={`/profile/${person.username}`}><b>{person.display_name||person.username}</b></Link><span>{online(person.last_seen_at)?"Online now":"Offline"}</span></div></header><div className="messageStream">{messages.length?messages.map(m=><div className={`messageBubble ${m.sender_id===me.id?"mine":"theirs"}`} key={m.id}><p>{m.content}</p><small>{new Date(m.created_at).toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small></div>):<div className="emptyThread"><span>✉</span><h3>Start the conversation</h3><p>Send {person.display_name||person.username} a message.</p></div>}<div ref={end}/></div><form className="messageComposer" onSubmit={send}><textarea maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder={`Message ${person.display_name||person.username}…`}/><button className="goldButton" disabled={busy||!text.trim()}>{busy?"Sending…":"Send"}</button></form></>:<div className="emptyThread"><span>✉</span><h3>Your messages</h3><p>Select someone to start chatting.</p></div>}</section></div>;
}