"use client";
import {FormEvent,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Donation={id:string;amount:number;method:string;status:string;created_at:string;profiles?:{username?:string;display_name?:string}|null};
const GCASH_NUMBER="09762113232";
const SUPPORT_AMOUNTS=[50,100,150,200,300,400,500,1000,1500,2500,5000,10000] as const;
export default function SupportClient({userId,credits,total,allTime,monthly,myDonations}:{userId:string;credits:number;total:number;allTime:Donation[];monthly:Donation[];myDonations:Donation[]}){
 const supabase=createClient();const [amount,setAmount]=useState("100");const [reference,setReference]=useState("");const [proof,setProof]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");const [qrOpen,setQrOpen]=useState(false);const [copied,setCopied]=useState(false);const file=useRef<HTMLInputElement>(null);
 async function copyNumber(){try{await navigator.clipboard.writeText(GCASH_NUMBER);setCopied(true);window.setTimeout(()=>setCopied(false),1600)}catch{setMsg(`GCash number: ${GCASH_NUMBER}`)}}
 async function gcash(e:FormEvent){e.preventDefault();const n=Number(amount);if(!SUPPORT_AMOUNTS.includes(n as any))return setMsg("Please choose one of the available support amounts.");if(!reference.trim())return setMsg("Enter your GCash reference number.");if(!proof)return setMsg("Upload your GCash receipt/screenshot.");setBusy(true);setMsg("");try{const ext=(proof.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"");const path=`${userId}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from("support-proofs").upload(path,proof,{contentType:proof.type});if(up.error)throw up.error;const ins=await supabase.from("support_donations").insert({user_id:userId,amount:n,method:"gcash",status:"pending",reference:reference.trim(),proof_path:path});if(ins.error)throw ins.error;setMsg("GCash support submitted! A Credits Support ticket was opened automatically in Orven Support. Your credits will be added after an admin verifies the payment.");setReference("");setProof(null);if(file.current)file.current.value="";}catch(x:any){setMsg(x.message||"Unable to submit GCash support.")}finally{setBusy(false)}}
 const board=(rows:Donation[])=>rows.length?rows.map((d,i)=><div className="supportRank" key={d.id}><b>#{i+1}</b><span>{d.profiles?.display_name||d.profiles?.username||"Orven member"}</span><strong>₱{Number(d.amount).toLocaleString()}</strong></div>):<p className="supportEmpty">No contributions yet.</p>;
 return <main className="supportPage"><section className="supportHero"><span>ORVEN COMMUNITY</span><h1>Support OrvenSMP</h1><p>Help us keep building the server, community and future experiences. Approved support is also returned to your account as Orven Credits for future use.</p><div className="supportTotals"><div><small>Total community support</small><strong>₱{total.toLocaleString()}</strong></div><div><small>Your Orven Credits</small><strong>₱{credits.toLocaleString()}</strong></div></div></section>
 <section className="supportPurpose" aria-label="How your support helps OrvenSMP">
  <div className="supportPurposeGlow supportPurposeGlowOne"/>
  <div className="supportPurposeGlow supportPurposeGlowTwo"/>
  <span className="supportPurposeEyebrow">YOUR SUPPORT BUILDS WHAT COMES NEXT</span>
  <h2>Help OrvenSMP grow stronger, smoother, and better.</h2>
  <p>Every contribution goes back into the community. Your support helps us maintain a stable home for players, continue developing new experiences, improve the server over time, and give OrvenSMP the resources it needs to keep moving forward.</p>
  <div className="supportPurposeItems">
   <div><i>01</i><b>Community Growth</b><small>Helping OrvenSMP expand, welcome more players, and build a stronger community.</small></div>
   <div><i>02</i><b>Server Stability</b><small>Supporting reliable infrastructure, upkeep, and a smoother experience for everyone.</small></div>
   <div><i>03</i><b>Development & Improvements</b><small>Fueling new features, better systems, updates, events, and future experiences.</small></div>
   <div><i>04</i><b>Continued Support</b><small>Keeping the project maintained, cared for, and moving forward for the long run.</small></div>
  </div>
  <strong className="supportPurposeClosing">You&apos;re not just donating — you&apos;re helping shape the future of OrvenSMP.</strong>
 </section>
 <div className="supportGrid"><section className="supportCard donateCard"><div className="gcashHeading"><div><span>GCASH SUPPORT</span><h2>Send your contribution</h2></div><b>Manual verification</b></div>
 <div className="supportAmountField"><span>Choose your support amount</span><div className="supportAmountOptions">{SUPPORT_AMOUNTS.map(n=><button key={n} type="button" className={Number(amount)===n?"selected":""} aria-pressed={Number(amount)===n} onClick={()=>setAmount(String(n))}>₱{n.toLocaleString()}</button>)}</div><small>Choose one amount below. Your selected amount will be verified against your GCash receipt.</small></div>
 <div className="gcashPaymentBox"><div className="gcashQrWrap"><img src="/support/gcash-instapay-qr.png" alt="GCash InstaPay QR code" onClick={()=>setQrOpen(true)}/><button type="button" onClick={()=>setQrOpen(true)}>View QR full size</button></div><div className="gcashDetails"><small>Send via GCash / InstaPay</small><strong>{GCASH_NUMBER}</strong><button type="button" className="gcashCopy" onClick={copyNumber}>{copied?"Copied!":"Copy number"}</button><p>Scan the QR code or send directly to the number above. After payment, enter the transaction reference and upload your receipt below.</p></div></div>
 <form onSubmit={gcash}><label>GCash reference number<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Enter the transaction reference"/></label><label>Payment receipt / screenshot<input ref={file} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setProof(e.target.files?.[0]||null)}/></label><button className="supportSubmit" disabled={busy}>{busy?"Submitting…":"Submit payment for verification"}</button></form>{msg&&<div className="supportMessage">{msg}{msg.startsWith("GCash support submitted!")&&<a href="/messages/support">Open Orven Support →</a>}</div>}
 <div className="gcashSteps"><b>How it works</b><ol><li>Send your chosen amount using the QR or GCash number.</li><li>Keep your successful transaction receipt.</li><li>Submit the reference number and receipt here.</li><li>Orven Support reviews the payment.</li><li>Once approved, the contribution is counted and the same amount is added to your Orven Credits.</li></ol></div><p className="supportFine">Never send your OTP, MPIN, password or other account credentials. Only your transaction reference and payment receipt are needed for verification.</p>
 <div className="paypalLater"><b>PayPal</b><span>Coming later — we&apos;re setting up GCash first.</span></div></section>
 <aside className="supportBoards"><section className="supportCard"><h2>Top supporters · All time</h2>{board(allTime)}</section><section className="supportCard"><h2>Top supporters · This month</h2>{board(monthly)}</section></aside></div>
 <section className="supportCard mySupport"><h2>Your support history</h2>{myDonations.length?<div className="supportHistory">{myDonations.map(d=><div key={d.id}><span>{new Date(d.created_at).toLocaleDateString()} · {d.method.toUpperCase()}</span><b>₱{Number(d.amount).toLocaleString()}</b><em className={`supportStatus ${d.status}`}>{d.status}</em></div>)}</div>:<p className="supportEmpty">You haven&apos;t submitted a contribution yet.</p>}</section>
 {qrOpen&&<div className="gcashQrModal" role="dialog" aria-modal="true" aria-label="GCash QR code" onClick={()=>setQrOpen(false)}><div className="gcashQrModalCard" onClick={e=>e.stopPropagation()}><button className="gcashQrClose" type="button" onClick={()=>setQrOpen(false)}>×</button><span>SCAN TO SUPPORT ORVENSMP</span><h2>GCash / InstaPay</h2><img src="/support/gcash-instapay-qr.png" alt="Large GCash InstaPay QR code"/><div className="gcashModalNumber"><strong>{GCASH_NUMBER}</strong><button type="button" onClick={copyNumber}>{copied?"Copied!":"Copy number"}</button></div><p>After sending, return here and submit your reference number and receipt for admin verification.</p></div></div>}
 </main>
}
