"use client";
import {FormEvent,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Donation={id:string;amount:number;method:string;status:string;created_at:string;profiles?:{username?:string;display_name?:string}|null};
const GCASH_NUMBER="09762113232";
const SUPPORT_AMOUNTS=[50,100,150,200,300,400,500,1000,1500,2500,5000,10000] as const;
type Modal="method"|"gcash"|null;
export default function SupportClient({userId,credits,total,allTime,monthly,myDonations}:{userId:string;credits:number;total:number;allTime:Donation[];monthly:Donation[];myDonations:Donation[]}){
 const supabase=createClient();
 const [amount,setAmount]=useState("100"),[reference,setReference]=useState(""),[proof,setProof]=useState<File|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[modal,setModal]=useState<Modal>(null),[qrOpen,setQrOpen]=useState(false),[copied,setCopied]=useState(false);const file=useRef<HTMLInputElement>(null);
 async function copyNumber(){try{await navigator.clipboard.writeText(GCASH_NUMBER);setCopied(true);window.setTimeout(()=>setCopied(false),1600)}catch{setMsg(`GCash number: ${GCASH_NUMBER}`)}}
 async function gcash(e:FormEvent){e.preventDefault();const n=Number(amount);if(!SUPPORT_AMOUNTS.includes(n as any))return setMsg("Please choose one of the available support amounts.");if(!reference.trim())return setMsg("Enter your GCash reference number.");if(!proof)return setMsg("Upload your GCash receipt/screenshot.");setBusy(true);setMsg("");try{const ext=(proof.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"");const path=`${userId}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from("support-proofs").upload(path,proof,{contentType:proof.type});if(up.error)throw up.error;const ins=await supabase.from("support_donations").insert({user_id:userId,amount:n,method:"gcash",status:"pending",reference:reference.trim(),proof_path:path});if(ins.error)throw ins.error;setMsg("Submitted! Your Credits Support conversation has been created in Orven Support for payment verification.");setReference("");setProof(null);if(file.current)file.current.value="";}catch(x:any){setMsg(x.message||"Unable to submit GCash support.")}finally{setBusy(false)}}
 const board=(rows:Donation[])=>rows.length?rows.map((d,i)=><div className={`supportRank cinematicRank rank${i+1}`} key={d.id}><b>#{i+1}</b><span>{d.profiles?.display_name||d.profiles?.username||"Orven member"}</span><strong>₱{Number(d.amount).toLocaleString()}</strong></div>):<p className="supportEmpty">No contributions yet. Be the first name on the board.</p>;
 return <main className="supportPage supportCinematicPage">
  <section className="supportFundHero">
   <div className="supportMedievalBackdrop" aria-hidden="true"/>
   <div className="supportHeroShade" aria-hidden="true"/>
   <div className="supportFundContent"><span className="supportFundEyebrow">ORVENSMP COMMUNITY FUND</span><small>TOTAL FUND COLLECTED</small><strong>₱{total.toLocaleString()}</strong><p>Every verified contribution helps us build what comes next.</p><button className="supportNowButton" onClick={()=>{setMsg("");setModal("method")}}>Support Now!</button></div>
  </section>

  <section className="supportAfterHero">
   <div className="supportLeaderboardArea">
    <div className="supportBoardPanel"><div className="supportBoardTitle"><span>ALL-TIME LEGENDS</span><h2>Top Supporters · All Time</h2></div>{board(allTime)}</div>
    <div className="supportBoardPanel"><div className="supportBoardTitle"><span>THIS MONTH</span><h2>Top Supporters · Monthly</h2></div>{board(monthly)}</div>
   </div>
   <aside className="supportCinematicClosing">
    <span>WHERE YOUR SUPPORT GOES</span><h2>Built by the community.<br/><em>For the community.</em></h2><p>Your support keeps OrvenSMP stable, funds continued development, helps us create new experiences and events, and gives the community room to grow.</p><div className="supportUseLines"><i>Server & Community Growth</i><i>Server Stability</i><i>Development & Improvements</i><i>Continued Support</i></div><strong>You&apos;re not just supporting a server — you&apos;re helping shape the future of OrvenSMP.</strong>
   </aside>
  </section>

  <section className="supportCard mySupport cinematicHistory"><div><span>YOUR CONTRIBUTIONS</span><h2>Support history</h2></div>{myDonations.length?<div className="supportHistory">{myDonations.map(d=><div key={d.id}><span>{new Date(d.created_at).toLocaleDateString()} · {d.method.toUpperCase()}</span><b>₱{Number(d.amount).toLocaleString()}</b><em className={`supportStatus ${d.status}`}>{d.status}</em></div>)}</div>:<p className="supportEmpty">You haven&apos;t submitted a contribution yet.</p>}</section>

  {modal&&<div className="supportModalBackdrop" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.currentTarget===e.target&&!busy)setModal(null)}}><div className={`supportFlowModal ${modal==="gcash"?"gcashFlowModal":""}`}>
   <button className="supportModalClose" type="button" disabled={busy} onClick={()=>setModal(null)}>×</button>
   {modal==="method"&&<><span className="supportModalEyebrow">SUPPORT ORVENSMP</span><h2>Choose your payment method</h2><p className="supportModalIntro">Select how you&apos;d like to support the community.</p><div className="supportPaymentChoices"><button className="paymentChoice gcashChoice" onClick={()=>setModal("gcash")}><div className="paymentChoiceIcon">G</div><div><b>GCash</b><small>Available · Manual verification</small></div><strong>→</strong></button><button className="paymentChoice paypalChoice" disabled><div className="paymentChoiceIcon">P</div><div><b>PayPal</b><small>Coming soon · Currently unavailable</small></div><em>SOON</em></button></div></>}
   {modal==="gcash"&&<><button className="supportBackButton" type="button" disabled={busy} onClick={()=>{setMsg("");setModal("method")}}>← Payment methods</button><span className="supportModalEyebrow">GCASH / INSTAPAY</span><h2>Support OrvenSMP</h2><p className="supportModalIntro">Scan the QR, send your selected amount, then upload your successful payment receipt for verification.</p><div className="gcashFlowGrid"><div className="gcashFlowQr"><button type="button" onClick={()=>setQrOpen(true)}><img src="/support/gcash-instapay-qr.png" alt="GCash InstaPay QR code"/></button><small>Click QR to enlarge</small><div><b>{GCASH_NUMBER}</b><button type="button" onClick={copyNumber}>{copied?"Copied!":"Copy"}</button></div></div><form className="gcashFlowForm" onSubmit={gcash}><label>How much are you sending?<select value={amount} onChange={e=>setAmount(e.target.value)}>{SUPPORT_AMOUNTS.map(n=><option value={n} key={n}>₱{n.toLocaleString()}</option>)}</select></label><label>GCash reference number<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Enter transaction reference"/></label><label className="proofUploadLabel">Upload proof of payment<input ref={file} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setProof(e.target.files?.[0]||null)}/><span>{proof?proof.name:"PNG, JPG or WEBP receipt / screenshot"}</span></label><button className="supportSubmit" disabled={busy}>{busy?"Submitting for approval…":"Submit for Approval"}</button></form></div>{msg&&<div className="supportMessage supportFlowMessage">{msg}{msg.startsWith("Submitted!")&&<a href="/messages/support">Open Orven Support →</a>}</div>}<p className="supportFine centeredFine">Never send your OTP, MPIN, password or account credentials. We only need the payment reference and receipt.</p></>}
  </div></div>}

  {qrOpen&&<div className="gcashQrModal" role="dialog" aria-modal="true" aria-label="GCash QR code" onClick={()=>setQrOpen(false)}><div className="gcashQrModalCard" onClick={e=>e.stopPropagation()}><button className="gcashQrClose" type="button" onClick={()=>setQrOpen(false)}>×</button><span>SCAN TO SUPPORT ORVENSMP</span><h2>GCash / InstaPay</h2><img src="/support/gcash-instapay-qr.png" alt="Large GCash InstaPay QR code"/><div className="gcashModalNumber"><strong>{GCASH_NUMBER}</strong><button type="button" onClick={copyNumber}>{copied?"Copied!":"Copy number"}</button></div></div></div>}
 </main>
}